# Testing the Linear Model trained in TensorFlow 

In [1]:
from __future__ import print_function
from link_bot_notebooks import notebook_finder
from link_bot_notebooks import toy_problem_optimization_common as tpo
import numpy as np
import matplotlib.pyplot as plt
from link_bot_notebooks.linear_tf_model import LinearTFModel

importing Jupyter notebook from /home/pmitrano/catkin_ws/src/link_bot/link_bot_notebooks/src/link_bot_notebooks/toy_problem_optimization_common.ipynb


In [2]:
goal = np.array([4, 0, 5, 0, 6, 0])
args = {'checkpoint': "../../log_data/November_21_00:16:38/nn.ckpt-15000", 'log': False}
dataset = "../../../link_bot_teleop/data/2_link_pos_and_vel_1.txt"
n, x, y = tpo.load_train_test(dataset, N=6, M=2, L=2, g=goal, extract_func=tpo.two_link_pos_vel_extractor)
model = LinearTFModel(args, N=6, M=2, L=2)
model.init()

INFO:tensorflow:Summary name A:0/gradient is illegal; using A_0/gradient instead.
INFO:tensorflow:Summary name B:0/gradient is illegal; using B_0/gradient instead.
INFO:tensorflow:Summary name C_1:0/gradient is illegal; using C_1_0/gradient instead.
INFO:tensorflow:Summary name D:0/gradient is illegal; using D_0/gradient instead.


In [3]:
A, B, C, D, c_loss, sp_loss, cp_loss, reg, loss = model.evaluate(x, y, display=True)

Cost Loss: 129.360702515
State Prediction Loss: 3.07889986038
Cost Prediction Loss: 29.5263404846
Regularization: 0.000492806197144
Overall Loss: 161.966430664
A:
[[ 0.19 -1.18  0.14 -0.12 -0.06 -0.07]
 [-0.24 -0.96 -1.06  0.19  0.4  -0.69]]
B:
[[-0.48 -0.42]]
C:
[[-0.59 -0.24]
 [ 0.66 -1.38]]
D:
[[ 0.85 -0.33]
 [-0.18  1.26]]


In [4]:
data = tpo.load_data(dataset, g=goal, extract_func=tpo.two_link_pos_vel_extractor)
print(data[0])

[array([[ 1.],
       [-2.],
       [ 2.],
       [-2.],
       [ 3.],
       [-2.]]), array([[-0.],
       [ 0.]]), array([[ 1.],
       [-2.],
       [ 2.],
       [-2.],
       [ 3.],
       [-2.]]), 12.99844355923877, 12.998006199699072]


In [5]:
tpo.plot_costmap(plt, model, data, goal, samples=20, spread=1)

ValueError: Cannot feed value of shape (6, 1) for Tensor u's:0', which has shape '(?, 6)'